/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_FFmpegUtils */

#ifndef _Included_com_example_ffmpeg_FFmpegUtils
#define _Included_com_example_ffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_FFmpegUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_ffmpeg_FFmpegUtils
 * Method:    paly
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpeg_FFmpegUtils_paly
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
